### ISSUE TITLE
It is not clear what belongs here

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Ecosystem#1]
It is not clear what belongs to this repo.

Suggestion:
- List links to other repos that do belong into Vulkan ecosystem.
- List examples of what is not handled elswhere and can be reported here.

**Comment by nsubtil** [comment]
We've updated the README to clarify the intent of this repo and are in the process of adding initial issues to the tracker. These should act as examples of the kind of problems we intend to track in this repository.

We're still in the process of setting things up, more information should become available in the next few weeks.
