### ISSUE TITLE
Better tutorial + resource guidance

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/Vulkan-Ecosystem#13]
One of the main struggles I see people having with Vulkan is simply trying to find good guidance on how to get started with Vulkan. There are now a number of useful tutorials and resources out there, but they often cater to different markets, or have various inobvious drawbacks (e.g. not being quite correct or performant); and it's hard to know where to turn.

Something that would be good is to work on giving better guidance on which tutorials can teach you what, what a given helper lib gives you, which audiences they cater to, what sort of drawbacks and benefits are you likely to get with each... etc.

This could almost take the form of a series of reviews and summaries of each resource.

Right now we have a number of lists such as http://stephaniehurlburt.com/blog/2017/7/14/beginner-friendly-vulkan-tutorials
and https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md, but these are fundamentally "just" lists - would be good to add some context to them.

**Comment by nsubtil** [comment]
From last week's discussion, the ecosystem group is willing to help curate documentation or any other resources that might be useful for Vulkan users.

@TobiasHector would you be willing to help put together an initial list of resources that should be looked at?

**Comment by HansKristian-Work** [comment]
From the call today, I can start going through the lists scattered around and lightly summarize what each tutorial/article goes through. I'll try to highlight some Vulkan code-bases out there as well.

Building context and evaluating the quality of the content is a larger task which needs to deferred to later.
I will link a google doc here once I have something substantial.

**Comment by plohrmann** [comment]
Here's a list of lots of resources that I found the other day: https://github.com/vinjn/awesome-vulkan

**Comment by nsubtil** [comment]
Some folks spent time doing an initial pass on this, and realized that just curating resources requires a lot of time and effort. There is growing concern about spending time on this topic as opposed to applying those resources towards, e.g., improving tools.

That said, this topic remains quite interesting. We're considering instead whether we can find a way to engage and motivate the community to fill this gap while we fix other more pressing issues within the Vulkan platform. We're not dropping this issue, however, as the hope is that we can still get back to this at a later time.

**Comment by vinjn** [comment]
Yeah, curating resources is hard. To be honest, I haven't done enough curating for awesome-vulkan.

**Comment by KarenGhavam-lunarG** [comment]
@nsubtil @sfricke-samsung Does the creation of the Vulkan Guide satisfy what is needed here (as long as it continues to get curated)?

**Comment by sfricke-samsung** [comment]
I think it depends what people are looking for.

For a general "what is Vulkan as this is the first time I have heard of it" I feel the Guide does a good job

How do I get up and going writing Vulkan Code, or How do graphics programming work, the Guide doesn't cross that scope boundary.

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website (https://www.vulkan.org) and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
