### ISSUE TITLE
README.md is misleading on spec copyright

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Ecosystem#25]
The license section says

> License: mixed — approximately: 
> proprietary Khronos license for the specification 
> Creative Commons Attribution 4.0 for document sources 
> Apache 2 for code

which could mislead people. I suggest replacing this with:

* Proprietary Khronos license for the Vulkan Specification published by Khronos on its website
* CC-BY 4.0 for asciidoctor sources for the Specification and related documents such as the reference pages, style guide, and XML schema documentation.
* Apache 2 for code, including the XML registry defining API interfaces

**Comment by KarenGhavam-lunarG** [comment]
Thanks Jon for your clarification. I will push this change for the Vulkan Specification in the Map of Vulkan Ecosystem projects.
