### ISSUE TITLE
Exposing combined image + sampler objects in HLSL

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-Ecosystem#33]
Using combined image samplers can be significantly more performant in some implementations when compared with separate image and sampler objects. However, there is currently no explicit way to use combined image samplers for HLSL shaders in Vulkan.

There is a post-processing pass in glslang which can combine textures and sampler objects depending on usage (see https://github.com/KhronosGroup/glslang/pull/856). However, it's not clear that having this done by a separate optimization pass is the best solution, since it requires host API changes depending on which objects end up being combined. And there seems to be no counterpart in dxc.

One idea would be to add a Vulkan-attribute that would turn a texture object into a combined image sampler. Something like:

```
[[vk::combinedImageSampler]] Texture2D<float4> myTexture;
Sampler mySampler;
...
myTexture.Sample(mySampler, uv);
```

`myTexture` would become a combined image sampler and the sampler parameter in the `Sample()` call would be ignored. The `mySampler` binding would then be eliminated based on existing rules for elimination of unused bindings. This could be done in addition to the optimization pass if that makes sense.

There are some variations on this, e.g., allowing the texture object itself to be passed in as the sampler argument instead, or declaring an implicit dummy sampler object to be used for combined image samplers.

Would like to start a discussion on how best to expose this. Does this proposal sound amenable? Do we want to do both explicit attributes as well as a separate optimization pass controlled by a command-line flag?

(Tagging @dneto0 @ehsannas @chaoticbob @antiagainst @johnkslang as potentially interested parties.)

**Comment by johnkslang** [comment]
Beyond liking to hear more about the need for this, some technical input:

- would use snake_case as being somewhat standard; maybe just `image_sampler`
- consider adding new prototypes that did not take a sampler parameter, rather than deal with dummy samplers and elimination passes

**Comment by dneto0** [comment]
The fundamental constraints are:
- we're dealing with existing shaders, in an existing language and its set of builtins and types.
- the change has implications at the API level (as you said), so there has to be a corresponding expression of intent. That motivates the need for a source annotation or something very prescriptive in terms of compiler options (which could get quite unwieldy).

Both constraints inform tradeoffs to possible directions.

For example, I would find your first proposal acceptable: it fits and captures the intentionality.  That would outweight the ugliness of having to write down the sampler that will be deliberately ignored anyway.
Maybe express the deliberateness of the throwaway as well:

Example: 
```
[[vk::combinedImageSampler]] Texture2D<float4> myTexture;
[[vk::ignore]] Sampler dummtSampler; 
...
myTexture.Sample(dummySampler, uv);
```
So a sampler can be used on a combined-image-sampler builtin if and only if the sampler has the "vk::ignore" attribute.

**Comment by johnkslang** [comment]
Are you expecting to get benefit without modifying shaders?

Today, a compiler can already statically see the combinations used, without having to modify them with the attribute syntax.

**Comment by nicebyte** [comment]
Hi, sorry to bump an old thread, but this topic is relevant to my interests as well.

I am trying to use HLSL as a language for authoring vulkan shaders; the inability to use a certain feature of the API (i.e. combined image/samplers) feels a bit restrictive.

 It also presents an inconvenience when cross-compiling HLSL for other APIs (i.e. OpenGL) which do not have full texture vs sampler separation at shader level. When using SPIRV-Cross, this can be addressed by auto-generating combined image/samplers and keeping a mapping  from separate to combined ids. 

However, if the goal is to actually have combined image/samplers in the output SPIR-V, that approach does not work.  From what I understand, some other developers have navigated around this problem by applying [transforms](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/Intermediate.cpp#L3841) to the AST.

I feel like having a special annotation similar to what's described above would make such usage scenarios much easier.

I also think that not having dummy samplers at all is more convenient - is there a reason to not prefer that approach?

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
