### ISSUE TITLE
Extending bit width control inside of GLSL

### ISSUE THREAD

**Issue by Cazadorro** [KhronosGroup/Vulkan-Ecosystem#34]
Suggestions to add new integer types in vulkan GLSL, such as int24/uint24 and int10/uint10 which map into 32bit float and 16bit float mantissas respectively, or potentially more control.  [Submitting based on the recommendation here.](https://github.com/KhronosGroup/Vulkan-Docs/issues/706#issuecomment-398022675)

Currently there are some architectures that exist where integer performance is worse that floating point performance.  For example, Nvidia hardware is like this and in CUDA, they've provided the ability to do 24bit integer arithmetic through [intrinsic functions](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT_1gffff4cfc8958ec96329c11a797146573) that take advantage of the mantissa of their floating point units.  Integer intensive operations could see a benefit from the utilization of either/both integer and floating point hardware if the programmer took careful consideration of the range of an 24bit integer. Some GPUs do not have 1:1 FPU to ALU which causes a difference in performance in favor of floating point operations.  Such optimizations may be possible with precision qualifiers in GLSL, but since it applies globally you would be ignoring integer ALUs potentially ([among normal small integer optimizations](https://devblogs.nvidia.com/mixed-precision-programming-cuda-8/)).  It is also unclear to me whether global precision qualifiers are still valid either in Vulkan or recent versions of OpenGL with GLSL. 

SPIR-V appears to [already support different bit widths](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_type_declaration_a_type_declaration_instructions) for float and integer types.  This would seem to indicate no changes to SPIR-V would need to be done in order for such an extension to be adopted. 

If one could specify the bits used in integers like so it could map directly into SPIR-V with out issue, and it would be up to the vendor to implement the JIT optimization that would utilize floating point units instead of integer units or what ever internal process they desire. 

It may be the case that instead of adding new syntax for only int24 and int10, since the same applies to int54, one should be able to arbitrarily specify bit width of their integers in glsl ie `int4`, `int18` `int8` etc... which may have further optimization effects for systems with multiple smaller arithmetic units for integers. This could take place in two different extensions for GLSL, one for up to 32bits and one for up to 64bits.

**Comment by krOoze** [comment]
> SPIR-V appears to already support different bit widths for float and integer types.

Only 32-bit is allowed by default, and Int8, Int16, and Int64 enabled by such named capability:

> Scalar integer types can be parameterized only as 32 bit, plus any additional sizes enabled by capabilities. 

<hr />

What would be the advantages over using `float` directly (with some high-precision decoration to avoid dangerous ops; i.e. fma)?

**Comment by Cazadorro** [comment]
>What would be the advantages over using float directly (with some high-precision decoration to avoid dangerous ops; i.e. fma)?

I'm not sure what you mean here, I was also under the impression that Nvidia 24bit mul was a special routine only using part of floating point hardware, but I could be wrong. In "faking it" I'm unsure the translation to SPIR-V would result in something the vendor JIT compiler would recognize as mantissa arithmetic, and may result in worse performance because of that.   

Not sure what you mean by "some high precision decoration" either.

**Comment by krOoze** [comment]
I mean just using regular (IEEE-754) `float`s for the same purpose, which also happen to have 24bit precision in that range. I.e. just storing the `int` as `float`: `float i = 42.0;`. It does not even need new HW. But it does need to be marked as high-precision, so the compiler avoids optimizations that are at the cost of precision (it would lose the "intness" of the values).

I can imagine storing it in mantissa can help bitops. But what else?
It might requre some new ops in the HW (or emulated), such as conversion from `int24` to `int32`, or `frexp`.

**Comment by johnkslang** [comment]
Note that GLSL features, and extensions that describe them, are developed at https://github.com/KhronosGroup/GLSL/ . If there is still a discussion about new bit widths, let's move it there.

**Comment by nsubtil** [comment]
@Cazadorro would you mind opening an issue in the KhronosGroup/GLSL repository? Seems like this issue requires some more technical discussion that would be best kept there.

**Comment by nsubtil** [comment]
@Cazadorro @johnkslang is this still relevant? I didn't see any issues for this in the GLSL repo, so not sure if this has been fixed in the meantime.

I can move this to the GLSL repo if that's the case.

**Comment by nsubtil** [comment]
Moved to https://github.com/KhronosGroup/GLSL/issues/38
