### ISSUE TITLE
Official 'getting started' page

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-Ecosystem#35]
From an issue forwarded by the Vulkan WG:

> THE most popular page on khronos.org by far is the OpenGL Getting Started Page:
> 
> https://www.khronos.org/opengl/wiki/Getting_Started
> 
> We should really have a corresponding Vulkan Getting Started page

**Comment by nsubtil** [comment]
This came up for discussion today. Summarizing our thoughts:

The OpenGL page is indeed really useful. It provides a high-level overview of what steps one needs to take to build an OpenGL app and links to detailed information on how to achieve each of these steps, from installing drivers to creating a GL context. It's the sort of information that a general graphics API book wouldn't necessarily cover very well and is essential in getting people off the ground --- even experienced graphics developers coming from another API will benefit from a resource like this.

The equivalent information on the Vulkan side already exists to some extent, and a lot of it is contained in the LunarG SDK documentation and a few other resources. However, it's somewhat scattered and in some cases written with a focus on desktop PC platforms (even if a lot of it does apply to other platforms as well).

We think there's a need for a landing page similar to the OpenGL Getting Started page. We also think this is a topic where the community could have a significant impact, so we'd like to put out a call for volunteers to help us bring this to fruition. If you have thoughts or would like to contribute an outline of what the page should look like, please reach out on this issue.

**Comment by krOoze** [comment]
There's a https://github.com/KhronosGroup/Vulkan-Docs/wiki
It invites to contribute, but I haven't figured out how to edit. Maybe it has permissions set only to members?

**Comment by KarenGhavam-lunarG** [comment]
@nsubtil @sfricke-samsung Does the creation of the Vulkan Guide resolve this issue?

**Comment by sfricke-samsung** [comment]
I would argue it does, it is the most "starting point" I think we can provide.

If we feel there is a need for a 'getting started" chapter then that can be raised in that repo imo

**Comment by sfricke-samsung** [comment]
Will let @nsubtil close the issue if feels this is good enough

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
