### ISSUE TITLE
Naming of an open source modern C++ Vulkan Scene Graph from the creator of OpenSceneGraph

### ISSUE THREAD

**Issue by XenonofArcticus** [KhronosGroup/Vulkan-Ecosystem#36]
On June 1st, Robert Osfield, the current head of the OpenSceneGraph project announced his initial work on a new open source scenegraph to succeed OpenSceneGraph written in purely modern C++ and designed specifically for Vulkan:

https://groups.google.com/forum/#!topic/osg-users/yaXTIc2wW8A

On behalf of the project, and Robert, we are seeking some definitive approval from someone at Khronos as to whether they would be in support of this project utilizing the descriptive name "Vulkan Scene Graph".

**Comment by robertosfield** [comment]
Thankyou for you attention.  As  project lead I can provide some clarifications, and a contact point if you have any questions or want to take discussions offline.

One area that needs clarification is the planned project name is VulkanSceneGraph, there are no plans to use the name "Vulkan Scene Graph".  The VulkanSceneGraph project name is our preferred name as this best reflects what this open source project will be - a Vulkan based Scene Graph.  It'll be the successor to the OpenScenGraph, long established as the OpenGL Scene Graph of choice for a range a markets such a vis-sim, VR, scientific visualisation and broadcast media.  It is my aim that the VulkanSceneGraph will provide a path for these markets to migrate smoothly to using Vulkan as their low level API of choice.    

In the same way that the OpenSceneGraph  has promoted use of OpenGL for nearly two decades, I hope this this new project will do the same for Vulkan and will be an asset to Khronos and the Vulkan/open API ecosystem.

This new project is just one month old now, we are still in the exploratory design and prototype stage.  Financially, technically and resource wise this open source project will be self funded ad run, as the OpenSceneGraph has been, so we don't need any direct technical assistance from Khronos.  At this stage all we'd like is awareness within Khronos that this effort is now underway. and if there any clarifications required on the use of Vulkan within the project name we sort these out.  I would also be useful to establish guidelines on how you'd want us to honour Vulkan trademarks etc when the time comes to us putting up websites and documentation - though we are a way off any of these things yet, so nothing is imminent.

I don't intended to trademark VulkanSceneGraph, and while don't have any specific logo plans, my intention will be take notes from the existing OpenSceneGraph font/colours rather mirror colour or style of Vulkan logo.  

This project is still very much in it's infancy, coding on the scene graph itself won't start in earnest till September (this year, 2018).  Alpha quality release might be available later this year, and perhaps a stable 1.0 release late 2019 if things progress well.  If you have any questions about the project then I'm a happy to answer them.  I'll be publishing a design white paper for the end of August and happy to share this.

**Comment by neiltrevett** [comment]
Hi Robert - great to hear that you are working on a Vulkan-based scene graph!  I am sure that this is something that Khronos and the Vulkan Working Group will want to coordinate with you on. Can you reach out to me at ntrevett@nvidia.com and we can figure out how we can best help?  Thanks!

**Comment by robertosfield** [comment]
Thanks Neil, will follow up via email.

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
