### ISSUE TITLE
About machine learning compute extension

### ISSUE THREAD

**Issue by nihui** [KhronosGroup/Vulkan-Ecosystem#45]
Hello, I saw a new effort on the "Vulkan state of the Union GDC Mar19" about that the Vulkan  ecosystem is working on exposing machine learning computing capabilities on modern GPU.
At the moment, our open-source project "ncnn" uses the Vulkan API to implement nerual network inference on GPU through writing lots of compute shaders. It has been working well on various platforms.
We've achieved better memory management and used extensions such as VK_KHR_16bit_storage and VK_KHR_shader_float16_int8 to get really good compute acceleration.
I think it would be better and run faster if we could use the new machine learning compute extension for the nerual network operator computing.
I am very interested in this and would like to get some more details and usage design of the extended interface.
Whether a separate pre-defined-command/pipeline (similar to CUDNN) has been designed for each nerual network operator ?
Whether an operator definition based on the current existing will be used for the operator parameter convention(such as ONNX or NNEF) ?
the ncnn community, as a potential target user, thank you very much for your fantastic efforts  :)

project link: https://github.com/Tencent/ncnn

**Comment by bhack** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=SIGGRAPH-2019-Vulkan-ML

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
