### ISSUE TITLE
[PETITION] Update tutorials

### ISSUE THREAD

**Issue by NervenCid** [KhronosGroup/Vulkan-Ecosystem#46]
Hello to all:

I'm new to trying to start learning Vulkan and i found some material:

https://vulkan-tutorial.com/
https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md

I checked some of the resources, but i believe that are a few outdated and are quite complex for beginners.

I wonder if it is possible, that khronos or someone make tutorials updated? i mean, nothing complex, just the basic installation and render a simple triangle or animation.

It is possible that khronos make a playlist in their youtube channel?

Thank you, and sorry for the english

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
