### ISSUE TITLE
Zipped version of the Specification Docs

### ISSUE THREAD

**Issue by Zingam** [KhronosGroup/Vulkan-Ecosystem#47]
Please make available the HTML API Reference Pages, the Vulkan 1.1 API Specifications (particularly the chunked versions) available as in a .ZIP archive for download:
https://www.khronos.org/registry/vulkan/

**Comment by oddhack** [comment]
You can download copies for offline use yourself with the Linux wget command. For example to retrieve the chunked specification

$ wget -r -p -np https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/index.html

Similarly for the refpages starting at https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/ .

**Comment by Zingam** [comment]
I already used another software to rip the docs. It took nearly an hour to process them and I still needed to do some manual tweaks to get the search working.

**Comment by oddhack** [comment]
Unless there's a lot more demand for this, we're unlikely to do it; we're instead trying to figure out how to best reduce the ridiculously large set of spec artifacts we're generating at each spec update.

I recommend that you download the spec repo and build the spec yourself for offline use - or use the PDFs. It takes far less than an hour to build the chunked HTML spec, once you have the toolchain set up.

**Comment by krOoze** [comment]
FYI, zip seems to now be available at https://vulkan.lunarg.com/doc/sdk. No refpages though.

**Comment by KarenGhavam-lunarG** [comment]
To clarify, all documentation for each SDK is online only at vulkan.lunarg.com. There was a request months back to be able to download all of the SDK documentation. So this zip found at vulkan.lunarg.com contains all of the SDK documentation for a specific SDK release. The specifications that are included in the zip are built for the selected header version. The SDKs don't include the reference pages, just html, pdf, and chunked.

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
