### ISSUE TITLE
Vulkan Driver/Explicit layer registry gone after windows 10 update

### ISSUE THREAD

**Issue by Imp07** [KhronosGroup/Vulkan-Ecosystem#48]
Im at a loss of what to do next. Vulkan was running fine before i shutoff my pc lastnight and let two new windows updates complete (a .netframework cumulative update and general windows 10 update).  Today I am getting registry lookup failures in vulkaninfo and noticed in my registry editor that all I have is ImplicitLayers listed under Vulkan > .

I have a ryzen5-3600 / Nvidia 1660TI / Windows 10 Pro OEM

I did a fresh reinstall with DDU + latest nvidia driver.  The driver folder is still not listed.  I downloaded the Vulkan RT installer.  At first it wont not install (vulkan.dll is already open in this folder).  I replaced the vulkan.dll with one found online and the RT installer was a success.  However the explicitlayer folder is still not installed and no libray files were installed as an app.

I believe it had to do with the windows 10 update.  So I was thinking to uninstall those updates and turn off auto updates, but it seems like my registry for vulkan is corrupted and short of a full windows 10 reinstall not sure how i can fix this...

**Comment by charles-lunarg** [comment]
When you say "Vulkan was running", do you mean vulkan applications fail to run? Ie, vkcube doesn't work, and vulkaninfo's only output is loader errors with no information about the devices on your system. Just from your description I can't really ascertain what the error is, could you post the output of vulkaninfo?

Also, did you have the Vulkan SDK installed? You could try reinstalling that if you haven't already. The SDK installer sets several registry values that may have been changed or reset by the windows or driver updates.

Do note that `HKEY_LOCAL_MACHINE\Software\Khronos\Vulkan\ExplicitLayers` shouldn't contain any driver related keys, as that has moved to a different registry location. Read the LoaderAndLayerInterface document for more details
https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#icd-discovery-on-windows

**Comment by Imp07** [comment]
Hi Charles thank you!  

I was able to run the SDK and now getinfo does not provide any registry error messages! 

I still have an odd issue with I think is the json file/nvidia loader.  I believe I know what the issue is but would like your input:

Game applications running vulkan are currently failling to run: vk_error_device lost.  

I checked online at what could be causing this issue and it seems that old loaders could be interrupting the ones installed by the latest nvidia card driver. 

For instance, If I check the System32 folder in Windows 10, I notice 2 duplicate json files for the nvidia loader, from 2019:

nv-vk64.json  - 2020-04-03
nv-vk32.json  -2020-04-03 

nv-vk64.json - 2019 -10-04
nv-vk32.json - 2019-10-04

So if I am understanding correctly, there should only be one json set (the one installed by a fresh nvidia driver install) and for whatever reason I have "stuck" old loaders that could be interfering.  Is my assumption correct?

**Comment by krOoze** [comment]
What are the full paths of the jsons? Might just be some temp files, or perhaps storage of some old driver from Windows Update.

Anyway what is conclusive is which json is referenced in `HKLM\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\XXXX` where `XXXX` is some number. Only `0000` should be there if you have only one GPU.

PS: You can run `vkvia` which extracts this kind of information and dumps it onto the Desktop as html.

**Comment by krOoze** [comment]
@Imp07 ping

**Comment by Imp07** [comment]
I found that there was just one entry... I assume it doesn't like something
when I'm connected to my tv vs being connected to my monitor.

Anyways this is resolved for now thanks!!!
