### ISSUE TITLE
KHR variants of NV_mesh_shader & other new equivalent DX12 Ultimate functionality?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/Vulkan-Ecosystem#49]
Hi,
just curious now that DX12 Ultimate is almost ready, and it's exposing more remaining Turing HW features, why we haven't got a clue of Vulkan cross vendor extensions of these new DX12 Ultimate features.. it's a little strange as at same time the NV Vulkan RT extension was announced it was announced also it was given to Khronos for working on a crossvendor extension.. now that we have in beta form the KHR raytracing extension seems next step are KHR mesh shader and "sampler feedback" extensions (NV_shader_image_footprint+ others?).. 
maybe it's a little soon and these new extensions will be announced at Siggraph this year.. not much later as this features are coming also to new AMD GPUs (RDNA2) pretty soon (Q3/Q4 2020)..
and we will know also pretty soon about new Intel Gen12 (Xe GPUs) which may support some features also..
thanks..

**Comment by kvark** [comment]
We are also interested in this in the context of a potential WebGPU extension for mesh shaders.

**Comment by oscarbg** [comment]
@kvark good to know.. unrelated to this issue but what about tesselation shaders.. any interest by WebGPU devs to expose even if only as an optional extension? I know still early days but it’s somewhat WebGPU extension mechanism already defined and documented already somewhere? I say this also because there is already a WebGPU “custom hack” enabling raytracing shaders also on WebGPU (https://github.com/maierfelix/chromium-ray-tracing ) with DXR and Vulkan back ends already implemented.. maybe with a little more work these effort could bring a official WebGPU raytracing extension(?)..

**Comment by kvark** [comment]
I should clarify that "we" here meant to be a few members of [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) community, not the whole WebGPU working group. "we" think that mesh shaders is potentially a better way forward than tessellation.
The actual working group is focused on delivering a minimum viable product of the API, so things like mesh shaders, tessellation, and raytracing, are deferred until after MVP.

**Comment by oscarbg** [comment]
thanks @kvark for clarification.. hope MVP can be delivered "soon enough" so we can start seeing some proposed experimental extensions not too far away :-)

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
