### ISSUE TITLE
Vulkan Quick Reference situation

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Ecosystem#5]
It is almost a year an Issue https://github.com/KhronosGroup/Vulkan-Docs/issues/418 was opened against Vulkan Quick Reference.

Can these pages be updated?

Should something be done to open more reliable communication channel to people responsible for the document? Or something else done to allow more rapid defect fixes (what is the copyright? can repo be opened for this)?

**Comment by oddhack** [comment]
There's an updated quick reference card being worked on, but it won't be published until late January at earliest.

**Comment by nsubtil** [comment]
@oddhack have there been any changes here? https://github.com/KhronosGroup/Vulkan-Docs/issues/418 is still open as far as I can tell.

**Comment by oddhack** [comment]
We released a 1.1 reference card along with the 1.1 spec, but I do not know how many of the issues reported were dealt with. I'll ping back on the reporter on Vulkan-Docs.

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website (https://www.vulkan.org) and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
