### ISSUE TITLE
Is vkCmdClearAttachments intentionally missing per-color channel masks?

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/Vulkan-Ecosystem#51]
On OpenGL this would clear all components in the first attachment except alpha:
```cpp
// DrawBuffer(COLOR_ATTACHMENT0);
ColorMaski(0, TRUE, TRUE, TRUE, FALSE);
Clear(COLOR_BUFFER_BIT);
```
Proprietary APIs have equivalent functionality inlined in what it'd be `ClearBuffer`. Vulkan seems to be missing an equivalent for this.

In the translation layer I work on there isn't a strong requirement for this at the moment, most applications seem to be fine without it. That said, I can't help but be curious about why this was left out of Vulkan. Was it an oversight or there are hardware vendors that can't implement it trivially?

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
