### ISSUE TITLE
Vulkan applications crash due to "Out of Memory" issues

### ISSUE THREAD

**Issue by sunnystormy** [KhronosGroup/Vulkan-Ecosystem#52]
I don't know if this is the right place to post this, and if there is a better place, please direct me there. :)

I've started using some WINE applications thru Linux, and they keep running out of memory due to the DXVK layer.

When an application runs, I get this output inside of the terminal:

```
info:  Intel(R) HD Graphics 530 (SKL GT2):
info:    Driver: 20.3.3
info:    Vulkan: 1.2.145
info:    Memory Heap[0]:
info:      Size: 11943 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:  llvmpipe (LLVM 11.0.1, 256 bits):
info:    Driver: 0.0.1
info:    Vulkan: 1.0.2
info:    Memory Heap[0]:
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
```

After piping my vulkan information into a text file, I noticed this:

```
VkPhysicalDeviceMemoryProperties:
=================================
memoryHeaps: count = 1
        memoryHeaps[0]:
                size   = 12523238400 (0x2ea717400) (11.66 GiB)
                budget = 12523143168 (0x2ea700000) (11.66 GiB)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT
```

Whereas my GL information is:

```
(GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x191b)
    Version: 20.3.3
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

Notice that the two memory sizes are *significantly* different. Is there a way to place a hard-cap on the memory for the Vulkan side of things? I would like to be able to play games without them running out of memory.

Thank you for your help!

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
