### ISSUE TITLE
Add compatibility \ driver bug avoidance layer?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Ecosystem#6]
On some Android devices, Vulkan drivers wont ever be updated.
On Windows less experienced users will have whatever the Windows Update gives, which would be ~half year old.
On Linux LTS you may also probably be on something that is god knows how old.

Firstly I would like to ask generally, if there is some strategy that should improve matters in the future.

Secondly I was thinking the Implementors could pool in their internal bug trackers and cooperate on making a compatibility layer that would, let's say, report a warning to the user if the API is used in a way that would expose a known driver bug that is in one of the drivers still known to be in circulation.

**Comment by HansKristian-Work** [comment]
For the second point, for bugs which can be checked statically from API level, this sounds like a very useful thing to have. Old drivers being far less mature than current drivers is something developers cannot ignore.

For our drivers, I started this thread: https://community.arm.com/graphics/f/discussions/9344/vulkan-driver-issues---workaround-collection-thread. Ideally, other IHV would have something similar so we could consider how to make it accessible through a "compat checking layer".

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website (https://www.vulkan.org) and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
